[build]
  Command = "npm run build"
  Functions = "lambda"
  Publish = "dist"

[[redirects]]
  from ="/rss.xml"
  to = "/.netlify/functions/rss"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
